-- (참고용) InterviewForge 는 전용 PostgreSQL "클러스터"를 새로 만들어 쓴다.
-- 클러스터 생성 + 포트/바인딩/비밀번호/DB/유저 설정은 모두 아래 스크립트가 처리한다:
--
--     sudo bash db/setup-cluster.sh
--
-- 이 SQL 파일은 더 이상 직접 실행할 필요가 없다. 테이블 스키마는 db/02_schema.sql 참고
-- (앱이 부팅할 때 자동 생성하므로 그것도 실행 불필요).
